// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpsuzitebosqylldefup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwc3V6aXRlYm9zcXlsbGRlZnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODQ3NDcsImV4cCI6MjA2OTQ2MDc0N30.SKuS35VAhDtge2_CdWAF0Xix90Xm2lV5xqvUdHNasmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});